i=int(input("enter a integer"))
f=float(input("enter a float"))
s=input("enter a string")
t=tuple(input("enter a tuple"))
b=(input("enter a boolean"))
print(type(i),i)
print(type(f),f)
print(type(s),s)
print(type(t),t)
print(type(b),b)
